services:
  - type: web
    name: srkr-smart-hostel
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://srkr-smart-hostel-5ave-n6uyv8ani-siva-0708.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
